version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydb
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: 123
      DB_NAME: mydb
