version: '3'
services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./src/config/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./ddl_pg.sql:/docker-entrypoint-initdb.d/ddl_pg.sql
    expose:
      - 5432

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db


volumes:
  postgres_data: